### ISSUE TITLE
[Bug]: Missing field for USER/PASS for SMB/CIFS

### ISSUE THREAD

**Issue by QuadrifoglioVerde** [ruaan-deysel/vault#82]
### Affected area

Web UI

### Related backup target

Not specific / not sure

### Vault version

2026.04.00

### Unraid version

7.2.4

### Storage backend

SMB

### What happened?

Missing field for entering username and passford for SMB access.

<img width="511" height="400" alt="Image" src="https://github.com/user-attachments/assets/3c6b68e7-3210-4a69-9224-5c15e6cb2d18" />

### Steps to reproduce

Just try add SMB/CIFS storage.

### Relevant log output

```shell

```

### Confirmation

- [x] I searched existing issues and discussions before opening this bug report.
- [x] I included enough detail for someone else to reproduce the issue.

**Comment by ruaan-deysel** [comment]
Hi, that's strange. I can see it just fine. Have you tried to uninstall and re-install the plugin?

<img width="524" height="567" alt="Image" src="https://github.com/user-attachments/assets/f8f02e59-5181-4ec8-a574-9f9b3b17390a" />

**Comment by QuadrifoglioVerde** [comment]
I try it just now, no change, tested on Brave browser but on Edge is situation same.
In debug console is this error on every Type change:

```
Uncaught TypeError: crypto.randomUUID is not a function
    at El (index-vmQTjv-9.js:3:101133)
    at _ (index-vmQTjv-9.js:9:1631)
    at index-vmQTjv-9.js:1:32845
    at or (index-vmQTjv-9.js:1:24857)
    at lr (index-vmQTjv-9.js:1:25945)
    at gn (index-vmQTjv-9.js:1:21412)
    at En (index-vmQTjv-9.js:1:22284)
    at Lr.ensure (index-vmQTjv-9.js:1:32838)
    at o (index-vmQTjv-9.js:1:33589)
    at index-vmQTjv-9.js:1:33635
El @ index-vmQTjv-9.js:3
_ @ index-vmQTjv-9.js:9
(anonymous) @ index-vmQTjv-9.js:1
or @ index-vmQTjv-9.js:1
lr @ index-vmQTjv-9.js:1
gn @ index-vmQTjv-9.js:1
En @ index-vmQTjv-9.js:1
ensure @ index-vmQTjv-9.js:1
o @ index-vmQTjv-9.js:1
(anonymous) @ index-vmQTjv-9.js:1
(anonymous) @ index-vmQTjv-9.js:9
(anonymous) @ index-vmQTjv-9.js:1
or @ index-vmQTjv-9.js:1
lr @ index-vmQTjv-9.js:1
#_ @ index-vmQTjv-9.js:1
#g @ index-vmQTjv-9.js:1
flush @ index-vmQTjv-9.js:1
(anonymous) @ index-vmQTjv-9.js:1
h @ index-vmQTjv-9.js:1
Ve @ index-vmQTjv-9.js:1
(anonymous) @ index-vmQTjv-9.js:1
```

**Comment by QuadrifoglioVerde** [comment]
I have same error in console when i try open settings page, just shows "Loading settings...", stopped working on 2026.04, in previous this works fine.

**Comment by ruaan-deysel** [comment]
Same root cause as #67 (`crypto.randomUUID is not a function` when the UI is served over plain HTTP — it's a secure-context restriction, not a browser-specific issue). Fix is already on `main` and will ship in the next release; the SMB user/pass fields will render normally once the new build is installed.

**Comment by ruaan-deysel** [comment]
Fixed in v2026.05.02 - see CHANGELOG . Closing; please reopen with a fresh report if you hit anything similar on the current release.
